[PicoXR] Enable WAKE_LOCK permission to allow app resuming
Otherwise application will crash due to the lack of that permission
whenever the application has to be resumed (for example after being
paused because the user removed the headset. This permission was
removed in the past because it was a requirement from the Meta
Store. We thought we could remove it for all the platforms but
apparently this is a real problem only for Pico.

This is the exception for reference

2023-05-11 12:24:57.396 31860-31860 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.igalia.wolvic.dev, PID: 31860
    java.lang.RuntimeException: Unable to resume activity {com.igalia.wolvic.dev/com.igalia.wolvic.VRBrowserActivity}:
    java.lang.SecurityException: Neither user 10191 nor current process has android.permission.WAKE_LOCK.
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4413)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4445)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2151)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:220)
        at android.app.ActivityThread.main(ActivityThread.java:7655)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)