Add a new proguard rule for an AC class
We're getting crashes on release builds like this:

java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to mozilla.components.concept.engine.manifest.WebAppManifest$Icon
at com.igalia.wolvic.ui.views.TabView$$ExternalSyntheticLambda1.apply(SourceFile:127)

The minification process was overoptimizing a map() call in an
ArrayList effectively removing the WebAppManifest class from the
final package. We need to add an exception to keep it.

Fixes #1297