[Chromium] Remove views from container on releaseDisplay()
Views are added to the container view on acquireDisplay().
Consequently those same views should be removed whenever
releaseDisplay() is called.

This fixes a crash when switching tabs with Chromium:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.igalia.wolvic.dev, PID: 22807
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5247)
        at android.view.ViewGroup.addView(ViewGroup.java:5076)
        at android.view.ViewGroup.addView(ViewGroup.java:5048)
        at com.igalia.wolvic.browser.api.impl.RuntimeImpl.addViewToBrowserContainer(RuntimeImpl.java:51)
        at com.igalia.wolvic.browser.api.impl.SessionImpl.acquireDisplay(SessionImpl.java:160)
        at com.igalia.wolvic.browser.engine.Session.surfaceChanged(Session.java:1804)

Fixes #795